version: "3"

services:
  nginx:
    build: ./.docker/nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - php

  php:
    build: ./.docker/php
    volumes:
      - ./src/public:/var/www/html/public
      # - ./src/vendor:/var/www/html/vendor
    env_file:
      - ./.env
    depends_on:
      - db
    working_dir: /var/www/html  

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./.docker/data/db:/var/lib/mysql
